# Generated by Django 3.0.6 on 2020-05-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('cart_desc', models.CharField(max_length=20)),
                ('short_desc', models.CharField(max_length=50)),
                ('long_desc', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('update_date', models.DateField(auto_now=True)),
                ('unlimited', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
