# Generated by Django 3.0.6 on 2020-05-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('productSKU', models.CharField(max_length=50)),
                ('productPrice', models.FloatField()),
                ('productCartDesc', models.CharField(max_length=20)),
                ('productShortDesc', models.CharField(max_length=50)),
                ('productLongDesc', models.CharField(max_length=200)),
                ('productImage', models.URLField()),
                ('productUpdateDate', models.DateField(auto_now=True)),
                ('productStock', models.IntegerField(max_length=5)),
                ('productUnlimited', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
