# Generated by Django 3.0.6 on 2020-05-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Niño'), (4, 'Accesorios')], default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='cart_desc',
            field=models.CharField(max_length=50),
        ),
    ]
