# Generated by Django 3.0.6 on 2020-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200530_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.TextField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('niño', 'Niño'), ('accesorios', 'Accesorios')], default='hombre'),
        ),
    ]
